export const GET_BILLING_ADDRESS="GET_BILLING_ADDRESS";
export const MESSAGE_CHANGE="MESSAGE_CHANGE";
export const CLICK_BUTTON="CLICK_BUTTON";
export const CANCEL_BUTTON="CANCEL_BUTTON";
export const USER_ACTION="USER_ACTION";
export const SET_SPINNER ="SET_SPINNER";
export const UPDATE_STATUS ="UPDATE_STATUS";
export const GET_COUNTRIES ="GET_COUNTRIES";
