export const RECURRINGBILLSELECTION={
    
    "ONE_MONTH": ["ONE_MONTH",1],
    "TWO_MONTHS": ["TWO_MONTHS",2],
    "THREE_MONTHS": [ "THREE_MONTHS", 3],
    "FOUR_MONTHS": [ "THREE_MONTHS", 4],
    "FIVE_MONTHS": [ "FIVE_MONTHS", 5],
    "SIX_MONTHS": [ "FIVE_MONTHS",  6],   
    "EIGHTEEN_MONTHS": [ "EIGHTEEN_MONTHS", 18 ],
    "ONE_YEAR": [ "ONE_YEAR", 1],
    "TWO_YEARS": [ "TWO_YEARS", 2],
    "THREE_YEARS":[ "THREE_YEARS", 3],
    "FOUR_YEARS": [ "FOUR_YEARS", 4],
    "FIVE_YEARS": [ "FIVE_YEARS", 5],
    "TEN_YEARS": [ "TEN_YEARS",10],

    WEEK:{ "WEEK":"WEEK"},
    MONTH:{ "MONTH":"WEMONTHEK"},
    DAYOFMONTH:{ "DAYOFMONTH":"DAYOFMONTH"},
   YEAR:{ "YEAR":"YEAR"}
}
   